- Dockerfile
- package-lock.json
- poetry.lock
- pyproject.toml
- src/app/lib/dependencies.py
- tests/unit/lib/test_dependencies.py
> fix: adds dependency tests

- .github/workflows/ci.yaml
- scripts/pre-build.py
- src/app/cli.py
- src/app/lib/worker/commands.py
- src/app/utils.py
Quick hack to support running on Windows natively with asyncio in place of uvloop.
> feat: rudimentary Windows support

- src/app/lib/exceptions.py
Handles #43 
Edit: whoever wants to please feel free to merge fixed tests into this PR
> fix(exceptions): handle breaking change from middleware updates to litestar

- src/app/lib/db/__init__.py
- src/app/lib/db/base.py
- tests/unit/lib/test_db.py
Uses the built-in auto-commit handler that's now in the Litestar repository.  This code is no longer required in fullstack. 
- 
-
> fix: use built in auto-commit handler

- .env.example
- .gitignore
- .pre-commit-config.yaml
- docker-compose.infra.yml
- package-lock.json
- poetry.lock
- scripts/pre-build.py
Adds an optional docker file that only starts the DB, Redis, and Mailhog.  This is useful for local development without containerizing the python and vite processes.
- 
-
> infra: adds docker compose for running redis, db, mailhog only

- README.md
- Fix typo re litestar-sqlalchemy in README
> docs: update README.md features

- .github/CODEOWNERS
- README.md
- docs/developer_guide/developer_setup.md
- mkdocs.yml
- pyproject.toml
- Update readme
- Fix ruff rule config
-
> meta: org updates

- src/app/domain/analytics/controllers.py
This PR corrects the aiosql imports
> fix: correct `aiosql` import

- .env.example
> fix: update ``.env`` ``alembic.ini`` path

- .sonarcloud.properties
- src/app/domain/plugins.py
- src/app/lib/dependencies.py
- tests/unit/lib/test_dependencies.py
> fix: handle default behaviour change in `CollectionFilter` for empty lists

- .pre-commit-config.yaml
- package-lock.json
- pdm.lock
- pyproject.toml
- src/app/__main__.py
This change adds a `__main__` entry point that sets the `LITESTAR_APP` environment variable.
Resolves #91 
Resolves #42
> feat: adds a custom entrypoint

- .pre-commit-config.yaml
- package-lock.json
- pdm.lock
- src/app/asgi.py
- src/app/domain/teams/services.py
- src/app/lib/crypt.py
- tests/docker_service.py
This fix addresses a few issues with the recent `AsyncCallable` changes.
> fix: updates for `AsyncCallable` changes

- docs/developer_guide/developer_setup.md
- 
- 
Native command doesn't work as is in the docs, it has an extra dash, see: https://pdm-project.org/latest/usage/dependency/
> docs: fix pdm install command

- docs/conf.py
-  Adds an `Edit on GitHub` button to the docs 
-
> docs: add an edit button to all pages

- .vscode/settings.json
- deploy/docker/dev/Dockerfile
- deploy/docker/run/Dockerfile
- docker-compose.override.yml
Docker build is failing because of a missing file reference.
> feat: remove `mkdocs` reference

- .pre-commit-config.yaml
- docs/index.rst
- package-lock.json
- pdm.lock
> chore: update docs and dependencies

- src/app/domain/tags/controllers.py
> chore: updated docstrings for `Tag` Controller

- .pre-commit-config.yaml
- package-lock.json
- package.json
- pdm.lock
- src/app/domain/web/controllers.py
- vite.config.ts
This PR adds additional configuration to the web controller to better handle client side routing.
> fix: routing correction

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- Makefile
- pyproject.toml
- tests/conftest.py
- tests/data_fixtures.py
- tests/docker-compose.yml
- tests/docker_service_fixtures.py
- tests/helpers.py
- tests/integration/conftest.py
Speed up the database testing service.
This PR:
* Refactor test framework code into separate files
* Add `SKIP_DOCKER_COMPOSE` option to tests
* Updated `Makefile` and Github Actions to start the database services before tests
* Adds `3.11` and `3.12` test pipeline
Latest test run in ~45 seconds
> chore: optimize database testing

- package-lock.json
- pdm.lock
- vite.config.ts
This ensures the HMR host is set to the `VITE_HOST` environment variable. 
-
> fix: set HMR host

- src/app/config/base.py
> fix: detect full driver name before configuring engine

- package-lock.json
- pdm.lock
This PR updates the `pytest-databases` dependencies
-
> chore: bump testing deps

- pdm.lock
- pyproject.toml
- src/app/db/models/oauth_account.py
- src/app/db/models/role.py
- src/app/db/models/tag.py
- src/app/db/models/team.py
- src/app/db/models/team_invitation.py
- src/app/db/models/team_member.py
- src/app/db/models/user.py
- src/app/db/models/user_role.py
> fix: upgrade AA and remove unnecessary ignores

- pdm.lock
- pyproject.toml
> chore: pin to latest litestar release

- .pre-commit-config.yaml
- package-lock.json
- pdm.lock
> chore: updated `advanced-alchemy` to `v0.11.1`

- .pre-commit-config.yaml
- package-lock.json
- pdm.lock
- src/app/domain/system/controllers.py
- src/app/domain/tags/controllers.py
- src/app/lib/exceptions.py
> fix: use signature_types to avoid exception

- src/app/config/base.py
> refactor: Use constant for true value check

- .pre-commit-config.yaml
- package-lock.json
- pdm.lock
- src/app/config/app.py
- src/app/lib/exceptions.py
> feat: upgrade advance alchemy

- .env.docker.example
- Fixes the following error
```ValueError: ALLOWED_CORS_ORIGINS is not a valid list representation.```
> fix: .env.docker.example missing quotes

- .pre-commit-config.yaml
- package-lock.json
- pdm.lock
- tests/integration/conftest.py
> chore: updated dependencies

- .pre-commit-config.yaml
- package-lock.json
- pdm.lock
- src/app/db/models/user.py
- src/app/domain/accounts/dependencies.py
- src/app/domain/accounts/repositories.py
- src/app/domain/accounts/schemas.py
- src/app/domain/accounts/services.py
- src/app/domain/teams/controllers/teams.py
- src/app/domain/teams/repositories.py
- src/app/domain/teams/services.py
- tests/helpers.py
> fix: remove `load` and `execution_options` from create

- .env.testing
- .pre-commit-config.yaml
- package-lock.json
- pdm.lock
- src/app/config/app.py
- src/app/config/base.py
- src/app/domain/accounts/guards.py
- src/app/domain/system/controllers.py
- src/app/domain/system/schemas.py
- tests/conftest.py
- tests/integration/conftest.py
- tests/integration/test_health.py
- tests/unit/conftest.py
Updates SAQ & uses the easier `autocommit` configuration.
> fix: updates current best practice

- src/app/domain/tags/controllers.py
- tests/integration/test_tags.py
This PR adds a test for the `list_tags` endpoints and adds a small fix to get the endpoint working.
> fix: correct annotation to `filters` dependency

- deploy/docker/run/Dockerfile.distroless
- docker-compose.override.yml
The `tsconfig.node.json` file was removed in https://github.com/litestar-org/litestar-fullstack/pull/193
This PR tidies up Docker to match.
> fix: Remove tsconfig.node.json from Docker

- Makefile
Same as https://github.com/litestar-org/advanced-alchemy/pull/343
> chore: don't clear pre-commit cache
