litestar-org/litestar-fullstack

- src/app/domain/accounts/models.py
- src/app/domain/accounts/schemas.py
https://github.com/cofin/starlite-full-stack-example/blob/master/src/app/lib/dependencies.py#L71
Before and After filters needing a model field `created` and `updated` - if not present, an `/api/users` call gives an error for field not found when filtering.
> FIX: fields for Before and After filters

- src/app/lib/settings.py
already prefixed above with `env_prefix = "DB_"`
> fix: remove extra DB_ prefix from a few settings

- tests/docker_service.py
Currently integration tests fail due to the `docker_service` timing out which itself is a result of the`docker compose` command not running correctly due to a shell error. This works on mac 13.2 with zsh & ohmyzsh. 
However I'm getting this on my own branch for Github Actions: 
Unsure if it's related to the changes on my PR.
> fix: docker compose shell command

- README.md
There was a missing dot in the command
> fix: update `cp .env` command in documentation

- deploy/docker/dev/Dockerfile
- deploy/docker/run/Dockerfile
- docker-compose.override.yml
This addresses an issue where the services launched in the containers are bound to listen on 127.0.0.1 instead of 0.0.0.0.
This prevented external access to container in most common network configurations.
- 
-
> infra: set host to `0.0.0.0` instead of `127.0.0.1`

- Makefile
Use `.` instead of `source` so that the `make install` command works on more shell configurations.
- 
-
> infra: fix `source` not found when running `make install`

- LICENSE
This PR modifies the license to MIT.  It now aligns with the other projects in `litesatr-org`
> chore: align license with litestar-org

- pdm.lock
- pyproject.toml
- tests/conftest.py
- tests/integration/test_access.py
- tests/integration/test_accounts.py
- tests/integration/test_teams.py
- tests/integration/test_tests.py
- tests/unit/lib/test_crypt.py
- tests/unit/lib/test_db.py
- tests/unit/lib/test_dependencies.py
- tests/unit/lib/test_log.py
Currently the async tests were skipped as no async test framework was available.
For some reason `pytest-asyncio` was still in the `pdm.lock` file and was installed initially until `pdm lock`.
This PR prepares the tests as needed for the `anyio` framework. As backend `asyncio` is used, as `anyio`'s default choice `trio` has issues with `asyncpg` (https://github.com/agronholm/anyio/issues/556)
> fix: Run async tests with `anyio` and `asyncio` backend

- tests/conftest.py
- tests/docker_service.py
- tests/integration/conftest.py
- tests/integration/test_tests.py
- tests/unit/conftest.py
- tests/unit/lib/test_cache.py
- tests/unit/lib/test_dependencies.py
- tests/unit/lib/test_exceptions.py
- tests/unit/lib/test_settings.py
This is a simple fix to remove a few pytest warnings.
> fix: adds anyio marker

- nixpacks.toml
Fullstack includes `nodeenv` and a PDM hook to build.  This means it will automatically build the assets correctly 
We don't need to also install and configure within Nix
> chore: update nixpack config

- README.md
- docker-compose.infra.yml
- docker-compose.override.yml
- docker-compose.yml
- nixpacks.toml
- railway.json
- src/app/lib/log/__init__.py
- src/app/lib/log/utils.py
fix: the correct a warning that was occurring on the JSON logger (only visible when no TTY).  This warning started appearing in the latest versions of structlog.
> fix: `structlog` corrections

- src/app/cli/commands.py
fixes:
```
(.venv) ~/tmp/litestar-fullstack main*
❯ app users create-user
Using Litestar app from env: 'app.asgi:app'
Loading environment configuration from .env
──────────────────────────────────────────────────────────────────────── Create a new application user. ────────────────────────────────────────────────────────────────────────
Email: darin@darin.com
Full Name: darin
Password: 
Repeat for confirmation: 
Create as superuser?: y
Traceback (most recent call last):
File "/home/darin/tmp/litestar-fullstack/.venv/bin/app", line 8, in <module>
sys.exit(run_cli())
^^^^^^^^^
File "/home/darin/tmp/litestar-fullstack/src/app/__main__.py", line 26, in run_cli
run_litestar_cli()
File "/home/darin/tmp/litestar-fullstack/.venv/lib/python3.12/site-packages/litestar/__main__.py", line 6, in …
```
> fix: use `to_dict` to convert to dict

- pyproject.toml
- src/app/config/app.py
- src/app/config/base.py
This PR sets the `SQLAlchemyAsyncConfig` to use the `db_engine` configured from settings.  This ensures things like DB Pool and SQL Print settings are read form the environment correctly.
> fix: use settings db engine instance

- tests/conftest.py
I think this is just an artefact of having used pytest-asyncio in the past.
- 
-
> test: remove event_loop fixture

- src/app/config/base.py
- [ X] Pre-Commit Checks were ran and passed
- [X ] Tests were ran and passed
Signature of one of the `_sqla_on_begin` method is invalid.
- 
Fixes #139 
-
> fix: signature for _sqla_on_begin method

- src/app/cli/commands.py
- [ X] Pre-Commit Checks were ran and passed
- [ X] Tests were ran and passed
Fix `app users promote-to-superuser` command not working because of use of `__dict__` instead of `to_dict()` method.
- 
Fixes #141 
-
> fix: Use to_dict method instead of __dict__ for UserUpdate

- .pre-commit-config.yaml
- .vscode/extensions.json
- package-lock.json
- pdm.lock
- pyproject.toml
- src/app/asgi.py
- src/app/db/models/oauth_account.py
- src/app/db/models/team_invitation.py
- src/app/db/models/team_member.py
- src/app/db/models/user_role.py
- src/app/domain/accounts/controllers/users.py
- src/app/domain/accounts/dependencies.py
- src/app/domain/accounts/schemas.py
- src/app/domain/accounts/services.py
- src/app/domain/accounts/signals.py
- src/app/domain/tags/controllers.py
- src/app/domain/teams/controllers/team_member.py
- src/app/domain/teams/controllers/teams.py
- src/app/domain/teams/guards.py
- src/app/domain/teams/repositories.py
- src/app/domain/teams/schemas.py
- src/app/domain/teams/services.py
- src/app/domain/teams/signals.py
- src/app/lib/dependencies.py
- src/app/lib/service.py
- tests/unit/lib/test_dependencies.py
Advanced Alchemy v0.8.2 will return the compatibility layer type from UUID Utils.  This means that all UUIDs are returned as a native type now.
> fix: use built in `UUID`

- src/app/lib/exceptions.py
- tests/unit/lib/test_exceptions.py
- [X ] New code has 100% test coverage
- [ X] Pre-Commit Checks were ran and passed
- [ X] Tests were ran and passed
I noticed in the `exception_to_http_response` that the way we check for exception was not valid.
We were using `isinstance` on the `http_exc` variable which is a class and not an instance which resulted in getting everytime we were on debug a 500 error even when we were supposed to ignore some exceptions.
> fix: invalid use of isinstance for HTTP exceptions checking

- src/app/domain/accounts/controllers/access.py
- tests/integration/test_access.py
- [X ] New code has 100% test coverage
- [ X] Pre-Commit Checks were ran and passed
- [ X] Tests were ran and passed
The `/api/access/logout` did not remove the cookie set in the clients (e.g browsers). So in a sense it did not allow someone to properyl "logout".
> fix: logout now correctly deletes cookie in client

- docker-compose.infra.yml
- docker-compose.override.yml
- docker-compose.yml
> feat: use valkey instead of redis

- docker-compose.infra.yml
- docker-compose.yml
Uses the correct name as seen in https://hub.docker.com/r/valkey/valkey/tags
> fix: typo in valkey image name

- src/app/config/constants.py
Remove the duplicated `DEFAULT_USER_ROLE` in constants.py, also delete the comment for favicon file.
> fix: remove duplicated constant in constants

- src/app/domain/web/controllers.py
From https://discord.com/channels/919193495116337154/1316783891683610685
Change `path=["/", "/{path:str}"]` to `path=["/", "/{path:path}"]`  in `WebController` to handle requests for all dynamic paths of any depth. It fixes cases where routes like `/posts` are handled but `/posts/1` are not.
> fix: handle dynamic routes of any depth for WebController

- .pre-commit-config.yaml
- package-lock.json
- src/app/domain/accounts/services.py
- src/app/domain/tags/dependencies.py
- src/app/domain/teams/services.py
- uv.lock
- Removed the `recursion_depth` parameter from the `selectinload` function in the `provide_tags_service` function.
- This resolves the `InvalidRequestError` caused by using `recursion_depth` in a non-self-referential relationship.
> fix: Remove recursion_depth from selectinload in TagService

- src/app/domain/teams/controllers/team_member.py
- src/app/domain/teams/services.py
- tests/integration/test_teams.py
This PR adds an unit test to the `teams/<id>/members/add` and `.../remove` endpoints, which are not working currently.
The endpoints were missing the `users_service` dependency, which was added.
In `TeamService` just the `tag_name` is passed to slugify, as this function accepts only strings.
> fix: Team add member
